import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { Manrope } from "next/font/google";
import { Covered_By_Your_Grace } from "next/font/google";
import { CartProvider } from "@/lib/context/CartContext";
import { ToastContainer } from "react-toastify";

const manrope = Manrope({
  subsets: ["latin"],
  variable: "--font-manrope",
  display: "swap",
  style: "normal",
});

const coveredByYourGrace = Covered_By_Your_Grace({
  subsets: ["latin"],
  variable: "--font-covered",
  weight: "400", // only one weight available
  display: "swap",
  style: "normal",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${manrope.className} ${coveredByYourGrace.className} ${manrope.variable} ${coveredByYourGrace.variable}`}
    >
      <ToastContainer
        position="top-right"
        autoClose={5000}
        hideProgressBar={true}
        newestOnTop={false}
        closeOnClick
        rtl={false}
        pauseOnFocusLoss
        draggable
        pauseOnHover
        closeButton={true}
        theme="light"
      />
      <CartProvider>
        <body style={{ fontFamily: "var(--font-manrope), sans-serif" }}>
          {/* Header */}
          <Header />

          {/* Main Content */}
          {children}

          {/* Footer */}
          <Footer />
        </body>
      </CartProvider>
    </html>
  );
}
